import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { StoreProvider, makeStore } from "@repo/store";
import { ConfigProvider } from "antd";
import HundleFullPage from "@/helper/get-page-url";
import { AuthProvider } from "@repo/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bremix Admin Panel",
  description: "Generated by Bremix Admin Panel",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  var { green, green_opcity_9 } = makeStore().getState().design;
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.syncfusion.com/ej2/26.1.35/material.css"
          rel="stylesheet"
        />
      </head>
      <body>
        <StoreProvider>
          <AuthProvider>
            <ConfigProvider
              theme={{
                components: {
                  Button: {
                    colorPrimary: green,
                    colorPrimaryTextHover: green,
                    colorPrimaryHover: green_opcity_9,
                  },
                  Switch: {
                    colorPrimary: green,
                    linkHoverDecoration: green,
                    colorPrimaryTextHover: green,
                    colorPrimaryHover: green_opcity_9,
                  },
                  Table: {
                    colorPrimary: green,
                    linkHoverDecoration: green,
                    colorPrimaryTextHover: green,
                    colorPrimaryHover: green_opcity_9,
                  },
                  Menu: {
                    colorPrimary: green,
                    linkHoverDecoration: green,
                    colorPrimaryTextHover: green,
                    colorPrimaryHover: green,
                  },
                  Input: {
                    colorPrimary: green,
                    linkHoverDecoration: green,
                    colorPrimaryTextHover: green,
                    colorPrimaryHover: green,
                  },
                },
              }}
            >
              <AntdRegistry>
                {children}
                <HundleFullPage />
              </AntdRegistry>
            </ConfigProvider>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
