import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getTokenPayload } from "@/helper/session";
import { cookies } from "next/headers";
import FullScreenLoader from "@/components/elements/full-screnn-loader/full-screnn-loader";
import HundleLanguage from "@/components/elements/hundle-language";
import { getSidebarItems } from "@/utils/sidebarItems";
import { AuthInitGate } from "@/components/auth/AuthInitGate";
import CmsLayoutClient from "./CmsLayoutClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bremix Admin Panel",
  description: "Generated by Bremix Admin Panel",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const token = cookieStore.get("access_token")?.value;

  const user: any = token ? await getTokenPayload(token) : null;

  return (
    <CmsLayoutClient sidebarItems={getSidebarItems(user.role)} user={user || {}}>
      <AuthInitGate>
        <FullScreenLoader />
        <HundleLanguage data={[]} />
        {children}
      </AuthInitGate>
    </CmsLayoutClient>
  );
}
