import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getTokenPayload } from "@/helper/session";
import { cookies } from "next/headers";
import FullScreenLoader from "@/components/elements/full-screnn-loader/full-screnn-loader";
import HundleLanguage from "@/components/elements/hundle-language";
import { AdminShell } from "@repo/shell";
import { getSidebarItems } from "@/utils/sidebarItems";
import QueryProvider from "@/components/common/QueryProvider";
import { AuthInitGate } from "@/components/auth/AuthInitGate";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bremix Admin Panel",
  description: "Generated by Bremix Admin Panel",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const token = cookieStore.get("access_token")?.value;

  const user: any = token ? await getTokenPayload(token) : null;

  return (
    <AdminShell sidebarItems={getSidebarItems(user.role)} user={user || {}}>
      <QueryProvider>
        <AuthInitGate>
          <FullScreenLoader />
          <HundleLanguage data={[]} />
          {children}
        </AuthInitGate>
      </QueryProvider>
    </AdminShell>
  );
}
