import type { ThemeConfig } from './types';

export const modernTheme: ThemeConfig = {
  token: {
    colorPrimary: '#F7931E',
    colorInfo: '#009FE3',
    colorSuccess: '#10B981',
    colorWarning: '#F59E0B',
    colorError: '#EF4444',
    colorLink: '#009FE3',

    colorBgLayout: '#FAFBFC',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgSpotlight: '#F3F4F6',
    colorBgMask: 'rgba(0, 0, 0, 0.45)',

    colorText: '#1F2937',
    colorTextSecondary: '#6B7280',
    colorTextTertiary: '#9CA3AF',
    colorTextQuaternary: '#D1D5DB',
    colorBorder: '#E5E7EB',
    colorBorderSecondary: '#F3F4F6',
    colorSplit: '#E5E7EB',

    borderRadius: 16,
    borderRadiusLG: 16,
    borderRadiusSM: 8,
    borderRadiusXS: 6,
    borderRadiusOuter: 20,

    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    fontSize: 14,
    fontSizeSM: 13,
    fontSizeLG: 16,
    fontSizeXL: 20,
    fontSizeHeading1: 32,
    fontSizeHeading2: 24,
    fontSizeHeading3: 20,
    fontSizeHeading4: 18,
    fontSizeHeading5: 16,

    lineHeight: 1.5,
    lineHeightHeading1: 1.2,
    lineHeightHeading2: 1.25,
    lineHeightHeading3: 1.3,

    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,

    paddingXXS: 4,
    paddingXS: 8,
    paddingSM: 12,
    padding: 16,
    paddingMD: 20,
    paddingLG: 24,
    paddingXL: 32,

    marginXXS: 4,
    marginXS: 8,
    marginSM: 12,
    margin: 16,
    marginMD: 20,
    marginLG: 24,
    marginXL: 32,

    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.04)',
    boxShadowSecondary: '0 4px 6px rgba(0, 0, 0, 0.04)',
    boxShadowTertiary: '0 10px 15px rgba(0, 0, 0, 0.04)',
  },
  components: {
    Layout: {
      siderBg: '#FFFFFF',
      headerBg: '#FFFFFF',
      bodyBg: '#FAFBFC',
      headerHeight: 64,
      headerPadding: '0 24px',
    },
    Menu: {
      itemBg: 'transparent',
      itemSelectedBg: '#FFF3E0',
      itemHoverBg: '#F9FAFB',
      itemSelectedColor: '#F7931E',
      itemColor: '#6B7280',
      itemHoverColor: '#F7931E',
      iconSize: 18,
      fontSize: 14,
      itemHeight: 44,
      itemMarginInline: 10,
      itemMarginBlock: 4,
      itemBorderRadius: 10,
      subMenuItemBg: 'transparent',
      groupTitleColor: '#9CA3AF',
      groupTitleFontSize: 11,
      collapsedIconSize: 18,
      popupBg: '#FFFFFF',
      radiusItem: 10,
      radiusSubMenuItem: 10,
    },
    Button: {
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      borderRadius: 10,
      borderRadiusLG: 12,
      borderRadiusSM: 8,
      primaryColor: '#FFFFFF',
      primaryShadow: '0 1px 2px rgba(0, 0, 0, 0.04)',
      defaultShadow: '0 1px 2px rgba(0, 0, 0, 0.04)',
      dangerShadow: '0 1px 2px rgba(0, 0, 0, 0.04)',
      fontWeight: 500,
      contentFontSize: 14,
      contentFontSizeLG: 16,
      contentFontSizeSM: 13,
      paddingInline: 20,
      paddingInlineLG: 24,
      paddingInlineSM: 12,
      onlyIconSize: 18,
      onlyIconSizeLG: 20,
      onlyIconSizeSM: 16,
    },
    Card: {
      colorBorderSecondary: '#E5E7EB',
      borderRadiusLG: 16,
      padding: 24,
      paddingLG: 24,
      paddingSM: 16,
      headerHeight: 56,
      headerFontSize: 16,
      headerPadding: '16px 24px',
      bodyPadding: 24,
      extraPadding: '16px 24px',
      actionsPadding: '16px 24px',
      actionsLiMargin: '0',
    },
    Table: {
      headerBg: '#F9FAFB',
      headerColor: '#6B7280',
      headerSortActiveBg: '#FFF3E0',
      headerSortHoverBg: '#F3F4F6',
      bodySortBg: '#FFFBEB',
      rowHoverBg: '#F9FAFB',
      rowSelectedBg: '#FFF3E0',
      rowSelectedHoverBg: '#FFF3E0',
      borderColor: '#E5E7EB',
      borderRadius: 16,
      headerBorderRadius: 16,
      cellPaddingBlock: 14,
      cellPaddingInline: 16,
      cellFontSize: 14,
      cellFontSizeMD: 13,
      cellFontSizeSM: 12,
      footerBg: '#F9FAFB',
      stickyScrollBarBg: '#E5E7EB',
      selectionColumnWidth: 48,
      expandIconBg: '#FFFFFF',
    },
    Input: {
      colorBgContainer: '#FFFFFF',
      colorBgContainerDisabled: '#F9FAFB',
      colorBorder: '#E5E7EB',
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      colorPrimaryActive: '#D47000',
      borderRadius: 10,
      borderRadiusLG: 12,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      paddingInline: 14,
      paddingBlock: 8,
      addonBg: '#F9FAFB',
      hoverBorderColor: '#F7931E',
      activeBorderColor: '#F7931E',
      activeShadow: '0 0 0 2px rgba(247, 147, 30, 0.1)',
      errorActiveShadow: '0 0 0 2px rgba(239, 68, 68, 0.1)',
      warningActiveShadow: '0 0 0 2px rgba(245, 158, 11, 0.1)',
      inputFontSize: 14,
      inputFontSizeLG: 16,
      inputFontSizeSM: 13,
    },
    Select: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E5E7EB',
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      borderRadius: 10,
      borderRadiusLG: 12,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      optionSelectedBg: '#FFF3E0',
      optionSelectedColor: '#F7931E',
      optionActiveBg: '#F9FAFB',
      optionFontSize: 14,
      optionHeight: 40,
      optionPadding: '8px 12px',
      selectorBg: '#FFFFFF',
      multipleItemBg: '#F9FAFB',
      multipleItemBorderColor: '#E5E7EB',
      showArrowPaddingInlineEnd: 36,
    },
    Dropdown: {
      colorBgElevated: '#FFFFFF',
      colorPrimary: '#F7931E',
      controlItemBgActive: '#FFF3E0',
      controlItemBgHover: '#F9FAFB',
      borderRadius: 12,
      borderRadiusLG: 12,
      controlPaddingHorizontal: 12,
      controlPaddingHorizontalSM: 8,
      paddingXXS: 4,
      paddingXS: 8,
      paddingSM: 12,
      fontSize: 14,
      lineHeight: 1.5,
      boxShadowSecondary: '0 10px 15px rgba(0, 0, 0, 0.04)',
    },
    Modal: {
      colorBgElevated: '#FFFFFF',
      borderRadiusLG: 16,
      borderRadiusSM: 8,
      borderRadiusXS: 6,
      headerBg: '#FFFFFF',
      titleFontSize: 18,
      titleColor: '#1F2937',
      contentBg: '#FFFFFF',
      footerBg: '#FFFFFF',
      headerPadding: '20px 24px 0',
      bodyPadding: 24,
      footerPadding: '16px 24px 20px',
      headerBorderBottom: '1px solid #E5E7EB',
      footerBorderTop: '1px solid #E5E7EB',
      paddingContentHorizontal: 24,
      paddingContentVertical: 20,
      paddingMD: 20,
      paddingLG: 24,
      padding: 16,
      marginXS: 8,
    },
    Tabs: {
      colorBgContainer: 'transparent',
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      colorPrimaryActive: '#D47000',
      inkBarColor: '#F7931E',
      itemColor: '#6B7280',
      itemHoverColor: '#F7931E',
      itemActiveColor: '#F7931E',
      itemSelectedColor: '#F7931E',
      titleFontSize: 14,
      titleFontSizeLG: 16,
      titleFontSizeSM: 13,
      horizontalMargin: '0 0 0 0',
      horizontalItemGutter: 4,
      horizontalItemPadding: '12px 16px',
      verticalItemPadding: '8px 16px',
      cardPadding: '8px 16px',
      cardBg: '#F9FAFB',
      cardGutter: 4,
      cardRadius: 10,
    },
    Breadcrumb: {
      colorBgTextHover: '#F9FAFB',
      colorText: '#6B7280',
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      fontSize: 13,
      iconFontSize: 14,
      itemColor: '#6B7280',
      lastItemColor: '#1F2937',
      linkColor: '#6B7280',
      linkHoverColor: '#F7931E',
      separatorColor: '#D1D5DB',
      separatorMargin: 8,
    },
    Tag: {
      colorPrimary: '#F7931E',
      colorSuccess: '#10B981',
      colorWarning: '#F59E0B',
      colorError: '#EF4444',
      colorInfo: '#009FE3',
      borderRadius: 6,
      fontSizeSM: 11,
      lineHeight: 1.5,
      defaultBg: '#F9FAFB',
      defaultColor: '#6B7280',
    },
    Badge: {
      colorPrimary: '#F7931E',
      colorSuccess: '#10B981',
      colorWarning: '#F59E0B',
      colorError: '#EF4444',
      colorInfo: '#009FE3',
      fontSize: 11,
      fontWeight: 600,
      textHeight: 18,
    },
    Spin: {
      colorPrimary: '#F7931E',
      dotSize: 32,
      dotSizeSM: 20,
      dotSizeLG: 48,
      fontSize: 14,
      fontSizeSM: 12,
      fontSizeLG: 16,
      contentHeight: 0,
    },
    Skeleton: {
      colorBgContainer: '#F3F4F6',
      colorFill: '#E5E7EB',
      borderRadius: 8,
      gradientFromColor: '#F3F4F6',
      gradientToColor: '#E5E7EB',
    },
    Empty: {
      colorPrimary: '#9CA3AF',
      colorTextDescription: '#6B7280',
    },
    Alert: {
      borderRadiusLG: 12,
      borderRadiusSM: 8,
      colorInfoBg: '#E3F2FD',
      colorInfoBorder: '#009FE3',
      colorSuccessBg: '#D1FAE5',
      colorSuccessBorder: '#10B981',
      colorWarningBg: '#FEF3C7',
      colorWarningBorder: '#F59E0B',
      colorErrorBg: '#FEE2E2',
      colorErrorBorder: '#EF4444',
      colorInfo: '#009FE3',
      colorSuccess: '#10B981',
      colorWarning: '#F59E0B',
      colorError: '#EF4444',
      withDescriptionPadding: '16px 20px',
      withDescriptionIconSize: 24,
    },
    Tooltip: {
      colorBgSpotlight: '#1F2937',
      colorText: '#FFFFFF',
      borderRadius: 8,
      fontSize: 13,
    },
    Popover: {
      colorBgElevated: '#FFFFFF',
      colorText: '#1F2937',
      borderRadius: 12,
      fontSize: 14,
      titleColor: '#1F2937',
      titleFontSize: 16,
      titleMinWidth: 176,
      boxShadowSecondary: '0 10px 15px rgba(0, 0, 0, 0.04)',
    },
    Notification: {
      colorBgElevated: '#FFFFFF',
      colorText: '#1F2937',
      colorTextHeading: '#1F2937',
      borderRadiusLG: 16,
      paddingMD: 20,
      paddingLG: 24,
      marginSM: 12,
      width: 384,
      progressBg: '#E5E7EB',
    },
    Steps: {
      colorPrimary: '#F7931E',
      colorText: '#1F2937',
      colorTextDescription: '#6B7280',
      colorTextDisabled: '#D1D5DB',
      colorFinish: '#10B981',
      colorError: '#EF4444',
      colorProcessBg: '#F7931E',
      colorWaitBg: '#E5E7EB',
      borderRadius: 9999,
      controlHeight: 32,
      customIconFontSize: 24,
      descriptionMaxWidth: 140,
      dotCurrentSize: 10,
      dotSize: 8,
      iconSize: 32,
      iconSizeSM: 24,
      iconFontSize: 16,
      iconFontSizeSM: 14,
      navArrowColor: '#F7931E',
      navContentMaxWidth: 'auto',
      nextIconSize: 14,
      progressDotSize: 8,
      titleSize: 14,
      titleSizeSM: 14,
    },
    Pagination: {
      colorBgContainer: '#FFFFFF',
      colorBgTextHover: '#F9FAFB',
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      borderRadius: 8,
      controlHeight: 36,
      controlHeightSM: 28,
      fontWeight: 500,
      fontSize: 14,
      fontSizeSM: 13,
      itemPadding: '0 8px',
      itemSize: 36,
      itemSizeSM: 28,
    },
    DatePicker: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E5E7EB',
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      borderRadius: 10,
      borderRadiusLG: 12,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      paddingInline: 14,
      activeBorderColor: '#F7931E',
      hoverBorderColor: '#F7931E',
      activeShadow: '0 0 0 2px rgba(247, 147, 30, 0.1)',
      cellHeight: 32,
      cellWidth: 36,
      cellHoverBg: '#F9FAFB',
      cellActiveWithRangeBg: '#FFF3E0',
      cellRangeBorderColor: 'transparent',
      panelBg: '#FFFFFF',
      inputFontSize: 14,
      timeColumnWidth: 56,
      timeColumnHeight: 32,
      yearCellHeight: 60,
      yearCellWidth: 80,
      monthCellHeight: 60,
      monthCellWidth: 80,
    },
    Switch: {
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      handleBg: '#FFFFFF',
      trackPadding: 2,
      trackMinWidth: 44,
      trackHeight: 24,
      innerMinMargin: 24,
    },
    Progress: {
      colorPrimary: '#F7931E',
      colorSuccess: '#10B981',
      colorWarning: '#F59E0B',
      colorError: '#EF4444',
      colorInfo: '#009FE3',
      borderRadius: 9999,
      defaultColor: '#F7931E',
      remainingColor: '#E5E7EB',
      textFontSize: 14,
      circleTextFontSize: 24,
      circleWidth: 120,
      circleWidthSM: 60,
      lineWidth: 8,
      lineWidthSM: 6,
      lineBorderRadius: 9999,
    },
    Radio: {
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      colorPrimaryActive: '#D47000',
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E5E7EB',
      borderRadius: 10,
      buttonBg: '#FFFFFF',
      buttonColor: '#6B7280',
      buttonPaddingInline: 16,
      buttonPaddingInlineLG: 20,
      buttonPaddingInlineSM: 12,
      dotSize: 16,
      dotSizeDisabled: 16,
      radioSize: 20,
      radioSizeSM: 16,
      radioSizeLG: 24,
      wrapperMarginInlineEnd: 8,
    },
    Checkbox: {
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      colorPrimaryActive: '#D47000',
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E5E7EB',
      borderRadius: 6,
      checkWidth: 18,
      checkWidthSM: 14,
      checkWidthLG: 22,
    },
    Upload: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E5E7EB',
      colorPrimary: '#F7931E',
      borderRadius: 10,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      actionsColor: '#6B7280',
      downloadIconColor: '#6B7280',
      fileCardBg: '#F9FAFB',
      fileListCardBg: '#F9FAFB',
      fileCardBorderRadius: 10,
      fileListCardBorderRadius: 10,
      pictureCardSize: 104,
      pictureCardSizeSM: 80,
      thumbnailSize: 48,
      thumbnailSizeSM: 40,
    },
    Drawer: {
      colorBgElevated: '#FFFFFF',
      colorText: '#1F2937',
      colorTextHeading: '#1F2937',
      borderRadiusLG: 16,
      headerBg: '#FFFFFF',
      headerPadding: '20px 24px',
      footerPadding: '16px 24px',
      bodyPadding: 24,
      paddingContentHorizontal: 24,
      paddingContentVertical: 20,
      paddingMD: 20,
      paddingLG: 24,
      marginXS: 8,
    },
    Divider: {
      colorBgContainer: '#FFFFFF',
      colorSplit: '#E5E7EB',
      fontSize: 14,
      fontSizeLG: 16,
      marginLG: 24,
      marginSM: 12,
      textPaddingInline: 16,
      verticalMarginInline: 8,
      orientationMargin: 0,
    },
    Collapse: {
      colorBgContainer: '#FFFFFF',
      colorBgContent: '#FFFFFF',
      colorBorder: '#E5E7EB',
      borderRadiusLG: 12,
      borderRadiusSM: 8,
      contentBg: '#FFFFFF',
      headerBg: '#F9FAFB',
      headerPadding: '14px 16px',
      contentPadding: '16px',
      collapseTitleFontSize: 14,
    },
    List: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E5E7EB',
      borderRadiusLG: 16,
      contentBg: '#FFFFFF',
      footerBg: 'transparent',
      headerBg: 'transparent',
      itemPadding: '16px 24px',
      metaAvatarSize: 40,
      metaDescriptionFontSize: 13,
      metaTitleFontSize: 14,
    },
    Statistic: {
      colorPrimary: '#F7931E',
      colorText: '#1F2937',
      contentFontSize: 28,
      titleFontSize: 14,
    },
    Descriptions: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E5E7EB',
      borderRadiusLG: 16,
      labelBg: '#F9FAFB',
      labelColor: '#6B7280',
      contentColor: '#1F2937',
      titleColor: '#1F2937',
      fontSize: 14,
      fontSizeSM: 13,
      labelFontSize: 13,
      titleFontSize: 16,
      titleMarginBottom: 16,
      itemPaddingBottom: 12,
      itemPaddingBottomSM: 8,
      colonMarginRight: 8,
      colonMarginLeft: 8,
      verticalPadding: 16,
    },
    Form: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#E5E7EB',
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      borderRadius: 10,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      labelColor: '#374151',
      labelFontSize: 14,
      labelHeight: 32,
      labelColonMarginInlineEnd: 8,
      itemMarginBottom: 24,
      itemMarginBottomLG: 24,
      itemMarginBottomSM: 16,
      paddingInline: 14,
      paddingXS: 8,
      verticalLabelMargin: 8,
      verticalLabelPadding: '0 0 4px',
    },
    Slider: {
      colorPrimary: '#F7931E',
      colorPrimaryBorder: '#F7931E',
      colorPrimaryBorderHover: '#E67E00',
      colorFill: '#E5E7EB',
      colorFillContent: '#F3F4F6',
      dotSize: 8,
      handleSize: 20,
      handleSizeHover: 24,
      handleLineWidth: 2,
      handleLineWidthHover: 3,
      railSize: 4,
      railBg: '#E5E7EB',
      railHoverBg: '#D1D5DB',
      trackBg: '#F7931E',
      trackHoverBg: '#E67E00',
    },
    Rate: {
      colorPrimary: '#F7931E',
      colorSecondary: '#E5E7EB',
      starSize: 20,
      starSizeSM: 14,
    },
    Tree: {
      colorBgContainer: '#FFFFFF',
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      borderRadius: 8,
      controlItemBgHover: '#F9FAFB',
      controlItemBgActive: '#FFF3E0',
      nodeHoverBg: '#F9FAFB',
      nodeSelectedBg: '#FFF3E0',
      nodePadding: 4,
      titleHeight: 36,
    },
    Avatar: {
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      colorBgContainer: '#FFF3E0',
      colorText: '#FFFFFF',
      colorTextPlaceholder: '#D1D5DB',
      borderRadius: 9999,
      containerSize: 40,
      containerSizeLG: 48,
      containerSizeSM: 32,
      groupOverlapping: -8,
      groupSpace: 0,
      groupBorderColor: '#FFFFFF',
    },
    Timeline: {
      colorBgContainer: '#FFFFFF',
      colorPrimary: '#F7931E',
      colorPrimaryBorder: '#F7931E',
      colorText: '#1F2937',
      colorTextDescription: '#6B7280',
      dotBg: '#FFFFFF',
      dotBorderWidth: 2,
      itemPaddingBottom: 24,
      tailColor: '#E5E7EB',
      tailWidth: 2,
      titleFontSize: 14,
    },
    Calendar: {
      colorBgContainer: '#FFFFFF',
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      colorText: '#1F2937',
      colorTextDisabled: '#D1D5DB',
      borderRadius: 16,
      cellHoverBg: '#F9FAFB',
      cellActiveBg: '#FFF3E0',
      fullCellHoverBg: '#F9FAFB',
      fullCellActiveBg: '#FFF3E0',
      yearCellHoverBg: '#F9FAFB',
      monthCellHoverBg: '#F9FAFB',
    },
    Segmented: {
      colorBgContainer: '#F3F4F6',
      colorPrimary: '#F7931E',
      colorPrimaryHover: '#E67E00',
      colorText: '#6B7280',
      colorTextLabel: '#6B7280',
      borderRadius: 10,
      borderRadiusLG: 12,
      borderRadiusSM: 8,
      controlHeight: 36,
      controlHeightLG: 44,
      controlHeightSM: 28,
      itemColor: '#6B7280',
      itemHoverColor: '#1F2937',
      itemSelectedBg: '#FFFFFF',
      itemSelectedColor: '#1F2937',
      trackBg: '#F3F4F6',
      trackPadding: 3,
    },
    Result: {
      colorPrimary: '#F7931E',
      colorSuccess: '#10B981',
      colorWarning: '#F59E0B',
      colorError: '#EF4444',
      colorInfo: '#009FE3',
      extraMargin: 24,
      iconFontSize: 72,
      subtitleFontSize: 14,
      titleFontSize: 24,
    },
    Watermark: {
      color: 'rgba(0, 0, 0, 0.15)',
      fontFamily:
        "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
      fontSize: 14,
    },
  },
};

export const darkTheme: ThemeConfig = {
  token: {
    colorPrimary: '#F7931E',
    colorInfo: '#009FE3',
    colorSuccess: '#34D399',
    colorWarning: '#FBBF24',
    colorError: '#F87171',
    colorLink: '#009FE3',

    colorBgLayout: '#0F1117',
    colorBgContainer: '#1A1D27',
    colorBgElevated: '#1A1D27',
    colorBgSpotlight: '#22252F',
    colorBgMask: 'rgba(0, 0, 0, 0.65)',

    colorText: '#F3F4F6',
    colorTextSecondary: '#9CA3AF',
    colorTextTertiary: '#6B7280',
    colorTextQuaternary: '#4B5563',
    colorBorder: '#2D3040',
    colorBorderSecondary: '#252838',
    colorSplit: '#2D3040',

    borderRadius: 16,
    borderRadiusLG: 16,
    borderRadiusSM: 8,
    borderRadiusXS: 6,
    borderRadiusOuter: 20,

    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",

    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.2)',
    boxShadowSecondary: '0 4px 6px rgba(0, 0, 0, 0.2)',
    boxShadowTertiary: '0 10px 15px rgba(0, 0, 0, 0.2)',
  },
  components: {
    Layout: {
      siderBg: '#1A1D27',
      headerBg: '#1A1D27',
      bodyBg: '#0F1117',
    },
    Menu: {
      itemBg: 'transparent',
      itemSelectedBg: '#3D2E00',
      itemHoverBg: '#22252F',
      itemSelectedColor: '#F7931E',
      itemColor: '#9CA3AF',
      itemHoverColor: '#F7931E',
      popupBg: '#1A1D27',
    },
    Card: {
      colorBorderSecondary: '#2D3040',
    },
    Table: {
      headerBg: '#22252F',
      headerColor: '#9CA3AF',
      bodySortBg: '#3D2E00',
      rowHoverBg: '#22252F',
      rowSelectedBg: '#3D2E00',
      borderColor: '#2D3040',
      footerBg: '#22252F',
      stickyScrollBarBg: '#2D3040',
      expandIconBg: '#1A1D27',
    },
    Input: {
      colorBgContainer: '#22252F',
      colorBgContainerDisabled: '#2A2D37',
      colorBorder: '#2D3040',
      addonBg: '#22252F',
      activeShadow: '0 0 0 2px rgba(247, 147, 30, 0.2)',
    },
    Select: {
      colorBgContainer: '#22252F',
      colorBorder: '#2D3040',
      optionSelectedBg: '#3D2E00',
      optionActiveBg: '#22252F',
      selectorBg: '#22252F',
      multipleItemBg: '#22252F',
      multipleItemBorderColor: '#2D3040',
    },
    Dropdown: {
      colorBgElevated: '#1A1D27',
      controlItemBgActive: '#3D2E00',
      controlItemBgHover: '#22252F',
      boxShadowSecondary: '0 10px 15px rgba(0, 0, 0, 0.2)',
    },
    Modal: {
      colorBgElevated: '#1A1D27',
      headerBg: '#1A1D27',
      contentBg: '#1A1D27',
      footerBg: '#1A1D27',
      headerBorderBottom: '1px solid #2D3040',
      footerBorderTop: '1px solid #2D3040',
    },
    Tabs: {
      cardBg: '#22252F',
    },
    Tag: {
      defaultBg: '#22252F',
      defaultColor: '#9CA3AF',
    },
    Skeleton: {
      colorBgContainer: '#22252F',
      colorFill: '#2D3040',
    },
    Alert: {
      colorInfoBg: '#002A3E',
      colorSuccessBg: '#064E3B',
      colorWarningBg: '#78350F',
      colorErrorBg: '#7F1D1D',
    },
    Tooltip: {
      colorBgSpotlight: '#F3F4F6',
      colorText: '#1F2937',
    },
    Popover: {
      colorBgElevated: '#1A1D27',
      boxShadowSecondary: '0 10px 15px rgba(0, 0, 0, 0.2)',
    },
    Notification: {
      colorBgElevated: '#1A1D27',
    },
    Drawer: {
      colorBgElevated: '#1A1D27',
      headerBg: '#1A1D27',
    },
    Empty: {
      colorPrimary: '#6B7280',
      colorTextDescription: '#6B7280',
    },
    Tree: {
      colorBgContainer: 'transparent',
      controlItemBgHover: '#22252F',
      controlItemBgActive: '#3D2E00',
      nodeHoverBg: '#22252F',
      nodeSelectedBg: '#3D2E00',
    },
    Avatar: {
      colorBgContainer: '#3D2E00',
      groupBorderColor: '#1A1D27',
    },
    Timeline: {
      dotBg: '#1A1D27',
      tailColor: '#2D3040',
    },
    Calendar: {
      colorBgContainer: 'transparent',
      colorTextDisabled: '#4B5563',
      cellHoverBg: '#22252F',
      cellActiveBg: '#3D2E00',
    },
    Segmented: {
      colorBgContainer: '#22252F',
      itemSelectedBg: '#1A1D27',
      trackBg: '#22252F',
    },
    Collapse: {
      colorBgContainer: '#1A1D27',
      colorBgContent: '#1A1D27',
      colorBorder: '#2D3040',
      contentBg: '#1A1D27',
      headerBg: '#22252F',
    },
    List: {
      colorBgContainer: 'transparent',
      colorBorder: '#2D3040',
      contentBg: 'transparent',
    },
    Descriptions: {
      colorBgContainer: 'transparent',
      colorBorder: '#2D3040',
      labelBg: '#22252F',
    },
    Form: {
      colorBgContainer: '#22252F',
      colorBorder: '#2D3040',
    },
    Pagination: {
      colorBgContainer: '#22252F',
      colorBgTextHover: '#22252F',
    },
    DatePicker: {
      colorBgContainer: '#22252F',
      colorBorder: '#2D3040',
      activeShadow: '0 0 0 2px rgba(247, 147, 30, 0.2)',
      cellHoverBg: '#22252F',
      cellActiveWithRangeBg: '#3D2E00',
      panelBg: '#1A1D27',
    },
    Steps: {
      colorWaitBg: '#2D3040',
    },
    Switch: {
      trackPadding: 2,
    },
    Slider: {
      colorFill: '#2D3040',
      colorFillContent: '#22252F',
      railBg: '#2D3040',
      railHoverBg: '#3D3040',
    },
    Radio: {
      colorBgContainer: '#22252F',
      colorBorder: '#2D3040',
      buttonBg: '#22252F',
    },
    Checkbox: {
      colorBgContainer: '#22252F',
      colorBorder: '#2D3040',
    },
    Upload: {
      colorBgContainer: '#22252F',
      colorBorder: '#2D3040',
      fileCardBg: '#22252F',
      fileListCardBg: '#22252F',
    },
    Progress: {
      remainingColor: '#2D3040',
    },
    Divider: {
      colorSplit: '#2D3040',
    },
  },
};