import {
  DashboardOutlined,
  FileTextOutlined,
  AppstoreOutlined,
  DatabaseOutlined,
  LinkOutlined,
  FormOutlined,
  LayoutOutlined,
  MenuOutlined,
  BuildOutlined,
  TagOutlined,
  ThunderboltOutlined,
} from "@ant-design/icons";
import type { AppMetadata } from "@repo/app-registry";

export const cmsAppMetadata: AppMetadata = {
  id: "cms",
  name: "CMS",
  description: "Content Management System",
  version: "1.0.0",
  icon: <FileTextOutlined />,
  baseRoute: "/admin",
  navigation: [
    {
      key: "cms-dashboard",
      label: "Overview",
      icon: <DashboardOutlined />,
      path: "/admin",
      description: "CMS Dashboard",
    },
    {
      key: "presets",
      label: "Presets",
      icon: <ThunderboltOutlined />,
      path: "/admin/presets",
      description: "Install website presets",
    },
    {
      key: "contents",
      label: "Contents",
      icon: <FileTextOutlined />,
      path: "/admin/contents",
      description: "Manage module contents",
    },
    {
      key: "pages",
      label: "Pages",
      icon: <FileTextOutlined />,
      path: "/admin/pages",
      description: "Manage pages",
    },
    {
      key: "navigations",
      label: "Navigations",
      icon: <AppstoreOutlined />,
      path: "/admin/navigations",
      description: "Manage navigation menus",
    },
    {
      key: "modules",
      label: "Modules",
      icon: <DatabaseOutlined />,
      path: "/admin/modules",
      description: "Manage content modules",
    },
    {
      key: "collections",
      label: "Collections",
      icon: <DatabaseOutlined />,
      path: "/admin/collections",
      description: "Manage collections",
    },
    {
      key: "relations",
      label: "Relations",
      icon: <LinkOutlined />,
      path: "/admin/relations",
      description: "Manage relations",
    },
    {
      key: "templates",
      label: "Templates",
      icon: <LayoutOutlined />,
      path: "/admin/templates",
      description: "Manage templates",
    },
    {
      key: "themes",
      label: "Themes",
      icon: <LayoutOutlined />,
      path: "/admin/themes",
      description: "Manage themes",
    },
    {
      key: "menus",
      label: "Menus",
      icon: <MenuOutlined />,
      path: "/admin/menus",
      description: "Manage menus",
    },
    {
      key: "components",
      label: "Components",
      icon: <BuildOutlined />,
      path: "/admin/components",
      description: "Manage components",
    },
    {
      key: "tags",
      label: "Tags",
      icon: <TagOutlined />,
      path: "/admin/tags",
      description: "Manage tags",
    }
  ],
};