import type { Metadata } from "next";
import { Inter } from "next/font/google";
import api_points from "@/api/points";
import { getTokenPayload } from "@/helper/session";
import { cookies } from "next/headers";
import api from "@/api/api-context";
import { repo_getLanguages } from "@/api/repostories/get-languages";
import FullScreenLoader from "@/components/elements/full-screnn-loader/full-screnn-loader";
import HundleLanguage from "@/components/elements/hundle-language";
import { toQueryString } from "@/helper/toQueryString";
import { AdminShell } from "@repo/shell";
import { getSidebarItems } from "@/utils/sidebarItems";
import QueryProvider from "@/components/common/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bremix Admin Panel",
  description: "Generated by Bremix Admin Panel",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const token = cookieStore.get("AuthToken")?.value;

  console.info("token : ", token);
  const user: any = await getTokenPayload(token ?? "");
  console.info("user : ", user);

  // const p = {
  //   pageSize: 20,
  //   currentPage: 1,
  //   search: "",
  //   sortField: "",
  //   sortOrder: "",
  //   isSingleton: false,
  // };

  // const response = await api.get(
  //   api_points.module.getAll + `?${toQueryString(p)}`,
  // );
  // const modules = await response.data;
  // const languages = await repo_getLanguages();

  return (
    <AdminShell sidebarItems={getSidebarItems(user.role)} user={user}>
      <QueryProvider>
        <FullScreenLoader />
        <HundleLanguage data={[]} />
        {children}
      </QueryProvider>
    </AdminShell>
  );
}
