import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getTokenPayload } from "@/helper/session";
import { cookies } from "next/headers";
import FullScreenLoader from "@/components/elements/full-screnn-loader/full-screnn-loader";
import HundleLanguage from "@/components/elements/hundle-language";
import { getSidebarItems } from "@/utils/sidebarItems";
import AdminLayoutClient from "./AdminLayoutClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bremix Admin Panel",
  description: "Generated by Bremix Admin Panel",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const token = cookieStore.get("AuthToken")?.value;

  const user: any = await getTokenPayload(token ?? "");

  return (
    <AdminLayoutClient sidebarItems={getSidebarItems(user.role)} user={user}>
      <FullScreenLoader />
      <HundleLanguage data={[]} />
      {children}
    </AdminLayoutClient>
  );
}
